version: "3.9"
services:
  ddbb:
    container_name: phones-ddbb
    image: mysql
    env_file:
      - ./mysql/.env
    ports:
      - "3309:3306"
    restart: unless-stopped
    volumes:
      - "./mysql/data/:/var/lib/mysql"
      - "./mysql/mysql-dump/schema.sql:/docker-entrypoint-initdb.d/schema.sql"
    networks:
      phone_network:

  api:
    container_name: phones-api
    hostname: phones-api
    image: phones-api
    env_file:
      - ./phones-api/.env
    environment:
      NODE_ENV: production
    depends_on:
      - ddbb
    ports:
      - "3005:3005"
    build:
      context: ./phones-api
      dockerfile: Dockerfile
    volumes:
      - "./phones-api/migration:/home/api/migration"
      - "./phones-api/mock:/home/api/mock"

    restart: unless-stopped
    command: node main
    networks:
      phone_network:
        ipv4_address: 172.25.0.3

  phones-app:
    container_name: phones-app
    image: phones-app
    depends_on:
      - api
    ports:
      - "8080:8080"
    build:
      context: ./phones-app/
      dockerfile: Dockerfile
    networks:
      phone_network:
        ipv4_address: 172.25.0.5
networks:
  phone_network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
